version: '3.7'
services:
  docker-mysql:
    restart: always
    container_name: docker-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: lalafood
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./src/main/resources/db:/docker-entrypoint-initdb.d
  order-taker:
    restart: on-failure
    image: order-taker
    build: ./
    ports:
      - "8080:8080"
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql